project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:
  title: "Nils Braakmann"
  site-url: "https://nilsbraakmann.github.io/nils-site/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    toc: true
