project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:
  title: "Nils Braakmann"
  site-url: "https://nilsbraakmann.github.io/nils-site/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: leadership.qmd
        text: Leadership
      - href: contact.qmd
        text: Contact
      - href: https://www.dropbox.com/scl/fi/pwlra56p5qgnsfm3jgwml/cv_short.pdf?rlkey=3xcc5ol8gobuhwgbkxdwrzdqi&dl=0
        text: CV

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
